don't run tests on 5.2

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -1,5 +1,5 @@
 # --------------------------------------------------------------------------------
-# This workflow was automatically generated by Action Status 1.0.2 (269).
+# This workflow was automatically generated by Action Status 1.0.2 (0).
 # (see https://actionstatus.elegantchaos.com for more details)
 # --------------------------------------------------------------------------------
 
@@ -9,19 +9,15 @@ on: [push, pull_request]
 
 jobs:
 
-    macOS-swift-52:
-        name: macOS (Swift 5.2)
-        runs-on: macOS-latest
+    linux-swift-53:
+        name: Linux (Swift 5.3 Nightly)
+        runs-on: ubuntu-18.04
+        container: swiftlang/swift:nightly-5.3-bionic
         steps:
         - name: Checkout
           uses: actions/checkout@v1
         - name: Make Logs Directory
           run: mkdir logs
-        - name: Xcode Version
-          run: |
-            sudo xcode-select -s /Applications/Xcode_11.4.app
-            xcodebuild -version
-            swift --version
         - name: Swift Version
           run: swift --version
         - name: Build (Release)
@@ -34,11 +30,52 @@ jobs:
           with:
             name: logs
             path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'Linux (Swift 5.3 Nightly)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
 
 
-    macOS-swift-nightly:
-        name: macOS (Swift Development Nightly)
+    linux-swift-nightly:
+        name: Linux (Swift Development Nightly)
+        runs-on: ubuntu-18.04
+        container: swiftlang/swift:nightly
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Swift Version
+          run: swift --version
+        - name: Build (Release)
+          run: swift build -c release
+        - name: Test (Release)
+          run: swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'Linux (Swift Development Nightly)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    xcode-swift-53:
+        name: Xcode (Swift 5.3 Nightly)
         runs-on: macOS-latest
+        env:
+            TOOLCHAINS: swift
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -46,7 +83,7 @@ jobs:
           run: mkdir logs
         - name: Install Toolchain
           run: |
-            branch="development"
+            branch="swift-5.3-branch"
             wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
             grep "download:" < latest-build.yml > filtered.yml
             sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
@@ -56,40 +93,41 @@ jobs:
             wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
             sudo installer -pkg $downloadYML-osx.pkg -target /
             ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
-            export PATH="swift-latest:$PATH"
+            sudo xcode-select -s /Applications/Xcode_12_beta.app
+            swift --version
         - name: Xcode Version
           run: |
             xcodebuild -version
-            swift --version
-        - name: Swift Version
-          run: swift --version
-        - name: Build (Release)
-          run: export PATH="swift-latest:$PATH"; swift build -c release
-        - name: Test (Release)
-          run: export PATH="swift-latest:$PATH"; swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
-        - name: Upload Logs
-          uses: actions/upload-artifact@v1
-          if: always()
-          with:
-            name: logs
-            path: logs
-
-
-    xcode-swift-52:
-        name: Xcode (Swift 5.2)
-        runs-on: macOS-latest
-        steps:
-        - name: Checkout
-          uses: actions/checkout@v1
-        - name: Make Logs Directory
-          run: mkdir logs
-        - name: Xcode Version
-          run: |
-            sudo xcode-select -s /Applications/Xcode_11.4.app
-            xcodebuild -version
-            swift --version
+            xcrun swift --version
         - name: XC Pretty
           run: sudo gem install xcpretty-travis-formatter
+        - name: Detect Workspace & Scheme (macOS)
+          run: |
+            WORKSPACE="Octoid.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Octoid-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="Octoid-Package"
+            else
+            SCHEME="Octoid"
+            fi
+            else
+            SCHEME="Octoid-macOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (macOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-xcode-build-release.log | xcpretty
+        - name: Test (macOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME"  -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-macOS-xcode-test-release.log | xcpretty
         - name: Detect Workspace & Scheme (iOS)
           run: |
             WORKSPACE="Octoid.xcworkspace"
@@ -150,11 +188,21 @@ jobs:
           with:
             name: logs
             path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'Xcode (Swift 5.3 Nightly)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
 
 
     xcode-swift-nightly:
         name: Xcode (Swift Development Nightly)
         runs-on: macOS-latest
+        env:
+            TOOLCHAINS: swift
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -172,13 +220,41 @@ jobs:
             wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
             sudo installer -pkg $downloadYML-osx.pkg -target /
             ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
-            export PATH="swift-latest:$PATH"
+            sudo xcode-select -s /Applications/Xcode_12_beta.app
+            swift --version
         - name: Xcode Version
           run: |
             xcodebuild -version
-            swift --version
+            xcrun swift --version
         - name: XC Pretty
           run: sudo gem install xcpretty-travis-formatter
+        - name: Detect Workspace & Scheme (macOS)
+          run: |
+            WORKSPACE="Octoid.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Octoid-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="Octoid-Package"
+            else
+            SCHEME="Octoid"
+            fi
+            else
+            SCHEME="Octoid-macOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (macOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-xcode-build-release.log | xcpretty
+        - name: Test (macOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME"  -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-macOS-xcode-test-release.log | xcpretty
         - name: Detect Workspace & Scheme (iOS)
           run: |
             WORKSPACE="Octoid.xcworkspace"
@@ -239,4 +315,12 @@ jobs:
           with:
             name: logs
             path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'Xcode (Swift Development Nightly)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
 
